### ISSUE TITLE
HtmlNode.Find and HtmlNodes.Find?

### ISSUE THREAD

**Issue by Upanc** [SoftCircuits/HtmlMonkey#1]
public static IEnumerable<HtmlNode> Find(this IEnumerable<HtmlNode> nodes, string expression);
public static IEnumerable<HtmlNode> Find(this HtmlNode node, string expression);

**Comment by SoftCircuits** [comment]
Is there a point to posting this?

**Comment by Upanc** [comment]
ScrapySharp
public static IEnumerable<HtmlNode> CssSelect(this IEnumerable<HtmlNode> nodes, string expression);
public static IEnumerable<HtmlNode> CssSelect(this HtmlNode node, string expression);

When I need to find elements in HtmlNode, it feels pretty neat
