### ISSUE TITLE
Having issues using Find to search for a div with specific class string

### ISSUE THREAD

**Issue by dpaulino** [SoftCircuits/HtmlMonkey#3]
Here's the div I'm trying to search for:

![image](https://github.com/SoftCircuits/HtmlMonkey/assets/7649589/c61762a0-ec6f-46ea-94b9-e3aaa10a06af)

This is how I'm attempting to find it: 
```csharp
var parent = document.Find("div.l-article__story l-main__story");
```

But `Find` is returning no results. Am I doing something wrong?

**Comment by dpaulino** [comment]
Never mind, solved it by doing this:

```csharp
textNodes = document.Find("div[class=\"l-article__story l-main__story\"]");
```

**Comment by SoftCircuits** [comment]
@dpaulino I think your original syntax was wrong. Classes are identified with a dot prefix. But you missed that with the second class name.

Looks like you found a solution though.

**Comment by dpaulino** [comment]
Ah so this would work? 

```csharp
var parent = document.Find("div .l-article__story .l-main__story");
```

**Comment by SoftCircuits** [comment]
@dpaulino Except you shouldn't need the div in that case.

https://stackoverflow.com/questions/1041344/how-can-i-select-an-element-with-multiple-classes-in-jquery
